# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9247f1db2da07b36e2bd3898083f2d3e8868cd058aff4388cfc14c622e353fb3ffa27ee66499fa459fc3e41509b737008d260a97371eab221381af505e3abfad

test:
  secret_key_base: 5224257eb326ac122543562cd79948e1c7e641a7b24b46b3c730188afcf18a15237e9259074a2945b2c0aa83474fcdf4c5a5540bf1f2e511eca3a4ed0f81de03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
